In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/dataset/Data.csv


In [2]:
# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing dataset
data = pd.read_csv('/kaggle/input/dataset/Data.csv')
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
print(x)

[['france' 44.0 72000.0]
 ['spain' 27.0 48000.0]
 ['germany' 30.0 54000.0]
 ['spain' 38.0 61000.0]
 ['germany' 40.0 nan]
 ['france' 35.0 58000.0]
 ['spain' nan 52000.0]
 ['france' 48.0 79000.0]
 ['germany' 50.0 83000.0]
 ['france' 37.0 87000.0]]


In [4]:
# Taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['france' 44.0 72000.0]
 ['spain' 27.0 48000.0]
 ['germany' 30.0 54000.0]
 ['spain' 38.0 61000.0]
 ['germany' 40.0 66000.0]
 ['france' 35.0 58000.0]
 ['spain' 38.77777777777778 52000.0]
 ['france' 48.0 79000.0]
 ['germany' 50.0 83000.0]
 ['france' 37.0 87000.0]]


In [5]:
# Encoding independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 66000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 87000.0]]


In [6]:
# Encoding dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [7]:
# Splitting into dataset into training set & test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [8]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 66000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [9]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 87000.0]]


In [10]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [11]:
print(y_test)

[0 1]
