In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-dataset/iris.data


In [2]:
import numpy as np
import pandas as pd

In [3]:
#url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
#names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
#dataset = pd.read_csv(url, names=names)
#dataset.head()

In [4]:
dataset = pd.read_csv('/kaggle/input/iris-dataset/iris.data')
dataset.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [5]:
x = dataset.drop('Iris-setosa', 1)
y = dataset['Iris-setosa']
print(x)
print(y)

     5.1  3.5  1.4  0.2
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  2.3
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
Name: Iris-setosa, Length: 149, dtype: object


/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [6]:
# Splitting dataset into training set & test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

from sklearn.decomposition import PCA
pca = PCA()
x_train = pca.fit_transform(x_train)
x_test = pca.fit_transform(x_test)
print(x_train)

[[-2.23539674e+00  2.13243304e-01 -2.70343602e-01  8.11635722e-02]
 [-5.07500873e-01 -1.60330404e+00  1.49361599e-01  1.90547238e-01]
 [ 5.02071965e-01 -1.75189190e-01 -2.98562950e-01 -2.19523369e-02]
 [ 6.47767286e-01  3.49762017e-01  6.05639099e-01 -9.03805782e-02]
 [-2.45705934e+00  1.00562833e+00  1.53044146e-01 -4.21834532e-02]
 [ 3.05848188e-01 -1.62438883e+00  9.47218844e-01 -1.48594912e-01]
 [ 1.26270990e+00  4.06976287e-01  1.62922934e-01 -2.19134996e-01]
 [ 5.19006822e-01 -1.76348912e+00 -8.25323645e-01  4.31343301e-02]
 [ 1.15895107e+00  6.21749445e-01 -5.74501933e-01  1.21367372e-02]
 [-2.38302139e+00 -7.11034264e-01  8.05977974e-02 -7.47040925e-02]
 [ 1.44029831e+00  2.60083654e-01  1.57087914e-01  1.16260882e-01]
 [-2.42222932e+00  1.58563339e-02  9.64457454e-02 -1.40548150e-01]
 [-5.42003628e-01 -1.91455450e+00  2.04350355e-01 -5.19481692e-02]
 [ 1.39168512e+00 -4.76844610e-01  9.74735777e-01  2.65342540e-01]
 [ 1.90245088e+00  1.03665700e+00  6.23012637e-01  2.10678676e

In [8]:
explained_variance = pca.explained_variance_ratio_
from sklearn.decomposition import PCA
pca = PCA(n_components = 1)
x_train = pca.fit_transform(x_train)
x_test = pca.fit_transform(x_test)
print(x_train)

[[-2.23539674]
 [-0.50750087]
 [ 0.50207197]
 [ 0.64776729]
 [-2.45705934]
 [ 0.30584819]
 [ 1.2627099 ]
 [ 0.51900682]
 [ 1.15895107]
 [-2.38302139]
 [ 1.44029831]
 [-2.42222932]
 [-0.54200363]
 [ 1.39168512]
 [ 1.90245088]
 [ 2.31421923]
 [ 0.09399481]
 [-0.10197712]
 [ 1.17711725]
 [ 1.7897892 ]
 [ 0.90381376]
 [ 0.21741705]
 [ 1.50523912]
 [ 1.08931019]
 [ 0.64350827]
 [ 0.94015508]
 [ 0.3601895 ]
 [-1.9281696 ]
 [-0.10984295]
 [ 0.27462498]
 [ 0.14323207]
 [ 0.99644489]
 [ 1.60749561]
 [ 0.18560066]
 [ 1.26569541]
 [-2.29566049]
 [-2.31989612]
 [ 2.1526171 ]
 [-0.41239303]
 [-2.31700138]
 [-2.32609854]
 [ 0.35744688]
 [-2.49461792]
 [ 1.71605039]
 [ 1.27933155]
 [-2.32881303]
 [ 0.10745581]
 [ 2.23030406]
 [ 0.22179496]
 [-2.71298182]
 [ 1.86855536]
 [ 1.27269705]
 [ 2.12595205]
 [ 1.10291821]
 [-2.48250714]
 [-2.29702477]
 [ 1.94999893]
 [ 1.19922924]
 [-2.64225664]
 [ 1.49875163]
 [-2.45238229]
 [ 1.53539209]
 [ 1.76721699]
 [-2.06701031]
 [-2.19343212]
 [ 1.78738281]
 [-2.01097

In [9]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(x_train, y_train)

# Predicting test set results
y_pred = classifier.predict(x_test)
print(y_train)

27         Iris-setosa
97     Iris-versicolor
96     Iris-versicolor
69     Iris-versicolor
18         Iris-setosa
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: Iris-setosa, Length: 119, dtype: object


In [10]:
print(y_pred)

['Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica']


In [11]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[12  0  0]
 [ 0  9  1]
 [ 0  0  8]]
0.9666666666666667
