In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris/Iris.csv
/kaggle/input/iris/database.sqlite


In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv('/kaggle/input/iris/Iris.csv')
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
x = dataset.drop('Species', 1)
y = dataset['Species']
print(x)
print(y)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virgin

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [5]:
# Splitting dataset into training set & test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

from sklearn.decomposition import PCA
pca = PCA()
x_train = pca.fit_transform(x_train)
x_test = pca.fit_transform(x_test)
print(x_train)

[[ 1.76504303e+00  3.46904352e-01 -5.46661983e-01 -2.26454630e-01
  -2.32344084e-01]
 [ 2.20233344e-01 -3.02686926e-01 -4.51538617e-01  4.81318999e-01
  -2.39944039e-01]
 [-2.45783315e+00  5.99759231e-01  1.04853057e-02 -1.87944451e-01
  -8.01484959e-04]
 [ 1.37146234e+00 -1.08555713e-05 -6.07099824e-01 -8.37902874e-02
  -2.21572565e-02]
 [ 2.14489278e+00 -2.67635149e-01 -3.65647464e-01  1.05633120e-01
   9.13053166e-02]
 [-2.52156099e-01 -1.03422430e+00 -5.94253319e-02  6.26038329e-01
  -1.15838193e-02]
 [-2.30865616e+00  1.47957481e+00  3.31186637e-01 -1.35171261e-01
   5.36561264e-02]
 [ 9.11700835e-01 -6.73048469e-01  2.33671398e-01  3.04524849e-01
  -1.80247843e-01]
 [ 1.51822675e-01 -7.31876083e-02  2.54855967e-01  4.60290658e-01
   5.07537186e-02]
 [ 3.71622426e-01 -1.02229422e+00  1.48432744e-02 -2.54432160e-01
  -1.63034207e-02]
 [ 1.95206653e+00  3.42833534e-01  1.31238503e-01  1.01720866e-01
   1.38593916e-01]
 [-2.90985785e+00 -2.50974343e-01  1.81818926e-01  2.60646472e-01

In [7]:
explained_variance = pca.explained_variance_ratio_
from sklearn.decomposition import PCA
pca = PCA(n_components = 1)
x_train = pca.fit_transform(x_train)
x_test = pca.fit_transform(x_test)
print(x_train)

[[ 1.76504303e+00]
 [ 2.20233344e-01]
 [-2.45783315e+00]
 [ 1.37146234e+00]
 [ 2.14489278e+00]
 [-2.52156099e-01]
 [-2.30865616e+00]
 [ 9.11700835e-01]
 [ 1.51822675e-01]
 [ 3.71622426e-01]
 [ 1.95206653e+00]
 [-2.90985785e+00]
 [ 2.28741295e+00]
 [-2.10086973e+00]
 [-2.63078543e+00]
 [-3.90263871e-01]
 [ 1.63883803e+00]
 [ 2.42106536e+00]
 [ 1.44657303e+00]
 [ 1.98461185e+00]
 [-3.07516830e-02]
 [ 2.98569545e+00]
 [ 3.77311559e-01]
 [ 5.39997954e-02]
 [ 1.57848565e+00]
 [ 1.50029697e+00]
 [ 5.61419037e-01]
 [ 2.01750804e+00]
 [ 6.03279894e-01]
 [ 2.01905890e+00]
 [ 4.25711312e-01]
 [-2.41890418e+00]
 [ 1.19609754e+00]
 [ 3.61635449e-01]
 [-2.31799919e-01]
 [ 2.92110892e-01]
 [ 6.33409225e-01]
 [ 2.15865189e+00]
 [-2.27261045e+00]
 [-3.03177931e+00]
 [ 1.68257273e+00]
 [ 2.16967139e-01]
 [-2.32136333e+00]
 [-2.62032984e+00]
 [ 7.42384242e-01]
 [-2.84701136e+00]
 [ 1.56051383e+00]
 [-2.42995024e-01]
 [-2.92139292e+00]
 [ 8.56994625e-01]
 [ 2.28080206e+00]
 [ 3.41057988e-01]
 [-2.6890732

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(x_train, y_train)

# Predicting test set results
y_pred = classifier.predict(x_test)
print(y_train)

137     Iris-virginica
84     Iris-versicolor
27         Iris-setosa
127     Iris-virginica
132     Iris-virginica
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: Species, Length: 120, dtype: object


In [9]:
print(y_pred)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica']


In [10]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[ 0  0 11]
 [ 2 11  0]
 [ 6  0  0]]
0.36666666666666664
